pip install --upgrade streamlit
pip install --upgrade scipy
pip install --upgrade matplotlib
pip install --upgrade numpy
pip install --upgrade pandas
pip install --upgrade seaborn
pip install --upgrade plotly
pip install --upgrade scikit-learn
pip install --upgrade yfinance
pip install --upgrade statsmodels
pip install --upgrade openpyxl
pip install --upgrade openai
pip install --upgrade folium
pip install --upgrade streamlit_folium
pip install --upgrade scikit-misc
pip install --upgrade cbsodata
pip install --upgrade polars
pip install --upgrade plotly-calplot